name: Build and Deploy Java Application

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  workflow_dispatch:  # Allow manual triggers

jobs:
  # Stage 1: Build
  build:
    name: Build Java Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: target/*.jar

  # Stage 2: Testing (requires approval for next stage)
  test:
    name: Test Java Code
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: test  # Reference the 'test' environment with an optional approval gate
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Tests
        run: mvn test

  # Stage 3: Deploy to Development
  deploy-Dev:
    name: Deploy to Dev Environment
    needs: test
    uses: ./.github/workflows/reusable-deploy.yml  # Reference the reusable workflow
    with:
      environment: dev

  # Stage 4: Deploy to Production (requires approval)
  deploy-Prod:
    name: Deploy to Production
    needs: deploy-Dev
    environment:
      name: production  # Reference the 'production' environment with an approval gate
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      environment: production
