name: Build and Deploy Java Application
on:
  push:
    branches:
      - feature-branch  # Replace with your target branch
    workflow_dispatch:

jobs:
  
  run-on-merge:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'Merge pull request')  # Check if the commit is a PR merge
    steps:
      - name: Run on PR merge
        run: echo "This workflow runs only when a pull request is merged."


  build:
    runs-on: ubuntu-latest
    steps:
      # Define environments in sequence
      - name: Set environment list
        id: envs
        run: echo "envs=dev,sit,prod" >> $GITHUB_ENV

      # Iterate over environments and call reusable workflows
      - name: Loop through environments
        run: |
          for env in $(echo ${{ env.envs }} | tr ',' ' '); do
            echo "Calling Workflow 1 for $env"
            gh workflow run reusable-test.yml --ref main --inputs env=$env
            
            echo "Calling Workflow 2 for $env"
            gh workflow run reusable-deploy.yml --ref main --inputs env=$env
          done

  # # Stage 1: Build
  # build:
  #   name: Build Java Code
  #   runs-on: ubuntu-latest
  #   needs: run-on-merge
  #   steps: 
  #     - name: Checkout Code
  #       uses: actions/checkout@v3

  #     - name: Set up JDK
  #       uses: actions/setup-java@v3
  #       with:
  #         distribution: 'adopt'
  #         java-version: '11'

  #     - name: Build with Maven
  #       run: mvn clean install

  #     - name: Upload Build Artifacts
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: build-artifacts
  #         path: target/*.jar

  # # Stage 3: Deploy to Development
  # deploy-dev:
  #   name: Deploy to Dev Environment
  #   needs: build
  #   uses: SakshiNadagoudra/Reusable-github-workflows/.github/workflows/reusable-deploy.yml@main # Reference the reusable workflow
  #   with:
  #     environment: dev  # Pass the environment name to the reusable workflow

  # test-sit:
  #   name: Test in SIT
  #   needs: deploy-dev
  #   uses: SakshiNadagoudra/Reusable-github-workflows/.github/workflows/reusable-test.yml@main
  #   with:
  #     environment: sit

  # # Stage 3: Deploy to Development
  # deploy-sit:
  #   name: Deploy to Sit Environment
  #   needs: test-sit
  #   uses: SakshiNadagoudra/Reusable-github-workflows/.github/workflows/reusable-deploy.yml@main  # Reference the reusable workflow
  #   with:
  #     environment: sit
  
  # test-uat:
  #   name: Test in Uat
  #   needs: deploy-sit
  #   uses: SakshiNadagoudra/Reusable-github-workflows/.github/workflows/reusable-test.yml@main
  #   with:
  #     environment: uat

  # # Stage 3: Deploy to Development
  # deploy-uat:
  #   name: Deploy to Uat Environment
  #   needs: test-uat
  #   uses: SakshiNadagoudra/Reusable-github-workflows/.github/workflows/reusable-deploy.yml@main  # Reference the reusable workflow
  #   with:
  #     environment: uat
  
  # test-prod:
  #   name: Test in Prod
  #   needs: deploy-uat
  #   uses: SakshiNadagoudra/Reusable-github-workflows/.github/workflows/reusable-test.yml@main
  #   with:
  #     environment: prod

  # # Stage 4: Deploy to Production
  # deploy-Prod:
  #   name: Deploy to Production Environment
  #   needs: test-prod
  #   uses: SakshiNadagoudra/Reusable-github-workflows/.github/workflows/reusable-deploy.yml@main  # Reference the reusable workflow
  #   with:
  #     environment: prod