name: Build and Deploy Java Application

on:
  push:
    branches:
      - feature-branch  # Replace with your target branch
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup GitHub CLI
        run: |
          echo "Setting up GitHub CLI"
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Trigger deployments
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
            environments=("dev" "sit" "uat" "prod")
            
            for env in "${environments[@]}"; do
              echo "Triggering deploy workflow for $env environment"
              gh workflow run reusable-deploy.yml -f environment=$env --ref ${{ github.ref }}
              
              # Wait for workflow to complete
              sleep 10  # Give time for workflow to start
              run_id=$(gh run list --workflow=reusable-deploy.yml --limit=1 --json databaseId --jq '.[0].databaseId')
              
              echo "Waiting for deploy workflow (ID: $run_id) to complete..."
              gh run watch $run_id
              
              if [ $? -eq 0 ]; then
                echo "Deploy to $env completed successfully"
                
                echo "Triggering test workflow for $env environment"
                gh workflow run reusable-test.yml -f environment=$env --ref ${{ github.ref }}
                
                # Wait for test workflow to complete
                sleep 10
                run_id=$(gh run list --workflow=reusable-test.yml --limit=1 --json databaseId --jq '.[0].databaseId')
                
                echo "Waiting for test workflow (ID: $run_id) to complete..."
                gh run watch $run_id
                
                if [ $? -ne 0 ]; then
                  echo "Tests failed for $env environment"
                  exit 1
                fi
              else
                echo "Deploy failed for $env environment"
                exit 1
              fi
            done