name: Build and Deploy Java Application

on:
  push:
    branches:
      - feature-branch  # Replace with your target branch
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup GitHub CLI
        run: |
          echo "Setting up GitHub CLI"
          sudo apt-get update
          sudo apt-get install -y gh

  
      - name: Trigger deployments
        env:
            GH_TOKEN: ${{ github.token }}
        run: |
            environments=("dev" "sit" "uat" "prod")
            
            for env in "${environments[@]}"; do
              echo "Starting deployment to $env environment"
              
              # Trigger deploy workflow
              gh workflow run reusable-deploy.yml -f environment=$env --ref ${{ github.ref }}
              
              if [ $? -ne 0 ]; then
                echo "Error: Failed to trigger deploy workflow for $env environment."
                exit 1
              fi
              
              sleep 10  # Wait for workflow to start
        
              # Get the run ID
              run_id=$(gh run list --workflow=reusable-deploy.yml --limit=1 --json databaseId --jq '.[0].databaseId')
              
              if [ -z "$run_id" ]; then
                echo "Error: Unable to retrieve the run ID for deploy workflow in $env environment."
                exit 1
              fi
        
              echo "Waiting for deploy workflow (ID: $run_id) to complete..."
              gh run watch $run_id --exit-status
              
              if [ $? -ne 0 ]; then
                echo "Deploy failed for $env environment."
                exit 1
              fi
              echo "✓ Deploy to $env completed successfully."
            done
        