name: Build and Deploy Java Application

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  workflow_dispatch:  # Allow manual triggers

jobs:
  # Stage 1: Build
  build:
    name: Build Java Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: target/*.jar

  test:
    name: Test Java Code
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: test  # Reference the test environment for approval gates
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Run Tests
        run: |
          echo "Running tests..."
          echo "This is a dummy test report for the POC." > test-report.txt

      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: test-report.txt

      - name: Notify Manager with Test Report and Approval Link
        uses: actions/github-script@v6
        with:
          script: |
            const workflowUrl = `https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}`;
            const approvalUrl = `https://github.com/${{ github.repository }}/environments/test/approval`;  # This URL could be used for manual approvals in GitHub environments
            const artifactUrl = `https://github.com/${{ github.repository }}/suites/${{ github.run_id }}/artifacts`;  // Artifact URL for download

            const message = `
              Hi there,

              Test execution is complete. Please review the test report:

              [Download Test Report](https://github.com/${{ github.repository }}/actions/artifacts/${{ github.run_id }}?name=test-report)

              Workflow details: ${workflowUrl}

              To approve and proceed to the next environment, please visit the following approval link:
              [Approve Deployment](https://github.com/${{ github.repository }}/environments/${{ inputs.environment }}/approval)
              
              Thanks,
              GitHub-BMO
            `;

            console.log(message);

            // Notify using GitHub API (e.g., comment on the commit)
            await github.rest.repos.createCommitComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.sha,
              body: message,
            });




  # Stage 3: Deploy to Development
  deploy-Dev:
    name: Deploy to Dev Environment
    needs: test
    uses: SakshiNadagoudra/Reusable-github-workflows/.github/workflows/reusable-deploy.yml@main  # Reference the reusable workflow
    with:
      environment: dev  # Pass the environment name to the reusable workflow

  # Stage 4: Deploy to Production
  deploy-Prod:
    name: Deploy to Production
    needs: deploy-Dev
    uses: SakshiNadagoudra/Reusable-github-workflows/.github/workflows/reusable-deploy.yml@main  # Reference the reusable workflow
    with:
      environment: production