name: Build, Deploy, and Test Sequentially

on:
  push:
    branches:
      - feature-branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: target/*.jar

  deploy-and-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup GitHub CLI
        run: |
          echo "Setting up GitHub CLI"
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Deploy and Test Sequentially
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          ENVIRONMENTS=("dev" "sit" "prod")
          for env in "${ENVIRONMENTS[@]}"; do
            echo "====================================="
            echo "Triggering Deploy workflow for $env"
            echo "====================================="

            # Trigger Deploy workflow
            gh workflow run reusable-deploy.yml --ref main -F environment=$env
            echo "Waiting for Deploy workflow to complete for $env..."

            # Wait for the deploy workflow to complete
            while true; do
              deploy_status=$(gh run list --workflow reusable-deploy.yml --json status,conclusion --jq '.[0]')
              if [[ "$deploy_status" == *"completed"* ]]; then
                conclusion=$(echo "$deploy_status" | jq -r '.conclusion')
                if [[ "$conclusion" != "success" ]]; then
                  echo "Deploy failed for $env. Exiting."
                  exit 1
                fi
                echo "Deploy successful for $env."
                break
              fi
              echo "Waiting for deploy to complete..."
              sleep 30
            done

            # Trigger Test workflow
            echo "====================================="
            echo "Triggering Test workflow for $env"
            echo "====================================="
            gh workflow run reusable-test.yml --ref main -F environment=$env

            echo "Waiting for Test workflow to complete for $env..."

            # Wait for the test workflow to complete
            while true; do
              test_status=$(gh run list --workflow reusable-test.yml --json status,conclusion --jq '.[0]')
              if [[ "$test_status" == *"completed"* ]]; then
                conclusion=$(echo "$test_status" | jq -r '.conclusion')
                if [[ "$conclusion" != "success" ]]; then
                  echo "Test failed for $env. Exiting."
                  exit 1
                fi
                echo "Test successful for $env."
                break
              fi
              echo "Waiting for test to complete..."
              sleep 30
            done
          done
