name: Build and Deploy Java Application

on:
  push:
    branches:
      - feature-branch  # Replace with your target branch
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup GitHub CLI
        run: |
          echo "Setting up GitHub CLI"
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Trigger deployments
        env:
            GH_TOKEN: ${{ github.token }}
        run: |
            environments=("dev" "sit" "uat" "prod")
            
            for env in "${environments[@]}"; do
              echo "Starting deployment to $env environment"
              
              # Trigger deploy workflow
              gh workflow run deploy.yml -f environment=$env --ref ${{ github.ref }}
              echo "Triggered deployment for $env"
              
              # Simple wait loop
              while true; do
                # Get status of latest run
                if gh run list --workflow=deploy.yml --limit 1 | grep -q "completed"; then
                  if gh run list --workflow=deploy.yml --limit 1 | grep -q "success"; then
                    echo "✓ Deploy to $env completed successfully"
                    break
                  else
                    echo "✗ Deploy to $env failed"
                    exit 1
                  fi
                fi
                echo "Waiting for deploy to complete..."
                sleep 10
              done
              
              echo "Starting tests for $env environment"
              gh workflow run test.yml -f environment=$env --ref ${{ github.ref }}
              echo "Triggered tests for $env"
              
              # Simple wait loop for tests
              while true; do
                # Get status of latest run
                if gh run list --workflow=test.yml --limit 1 | grep -q "completed"; then
                  if gh run list --workflow=test.yml --limit 1 | grep -q "success"; then
                    echo "✓ Tests for $env completed successfully"
                    break
                  else
                    echo "✗ Tests for $env failed"
                    exit 1
                  fi
                fi
                echo "Waiting for tests to complete..."
                sleep 10
              done
              
              echo "----------------------------------------"
            done
  