name: Build and Deploy Java Application

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build:
    name: Build Java Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: target/*.jar

  # approval:
  #   name: Request Manager Approval
  #   needs: build
  #   uses: ./.github/workflows/reusable-approval.yml  # Reference reusable workflow
  #   with:
  #     approvers: "manager-github-username"  # Replace with the manager's GitHub username

  deploy:
    name: Deploy Application
    needs: build
    uses: ./.github/workflows/reusable-deploy.yml # Reference reusable workflow
    with:
      environment: dev

# name: Multi-stage Deployment with Approval

# on:
#   push:
#     branches:
#       - main  # Trigger when pushing to the main branch
#   workflow_dispatch:  # Allows manual trigger from GitHub UI

# jobs:
#   # Stage 1: Build
#   build:
#     runs-on: ubuntu-latest
#     environment: build # This can be linked to an environment for auditing
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up JDK
#         uses: actions/setup-java@v3
#         with:
#           distribution: 'adopt'
#           java-version: '11'

#       - name: Build with Maven
#         run: mvn clean install

#       - name: Upload Build Artifacts
#         uses: actions/upload-artifact@v3
#         with:
#           name: build-artifacts
#           path: target/*.jar

#   # Stage 2: Testing (requires manual approval)
#   test:
#     runs-on: ubuntu-latest
#     needs: build
#     environment: test  # This environment can have an approval gate
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Run Tests
#         run: mvn test

#   # Stage 3: Production (requires manual approval from manager)
#   deploy-to-production:
#     needs: test
#     environment: production  # This environment requires approval
#     uses: ./.github/workflows/reusable-deploy.yml  # Reference reusable workflow
#       with:
#         environment: production  # Pass the environment input to the reusable workflow
