name: Build and Deploy Java Application

on:
  push:
    branches:
      - feature-branch  # Replace with your target branch
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup GitHub CLI
        run: |
          echo "Setting up GitHub CLI"
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Deploy and Test Sequentially with Approval
        env:
          GH_TOKEN: ${{ github.token }}  # Set the GH_TOKEN environment variable
        run: |
          # Define environments
          ENVIRONMENTS=("dev" "sit" "prod")
          
          # Loop through each environment
          for env in "${ENVIRONMENTS[@]}"; do
            # Step 1: Trigger Deploy workflow for the current environment
            echo "====================================="
            echo "Triggering Deploy workflow for $env"
            echo "====================================="
            deploy_output=$(gh workflow run reusable-deploy.yml --ref feature-branch -F environment=$env)
            echo "$deploy_output"  # Debugging output to ensure the workflow is triggered
            
            echo "Waiting for deploy workflow ($env) to complete..."

            # Step 2: Wait for approval if environment is not 'dev'
            if [ "$env" != "dev" ]; then
              echo "====================================="
              echo "Waiting for manual approval for $env"
              echo "====================================="
              # GitHub will automatically pause here and wait for manual approval
              # Monitor the approval status by checking the deployment status for environment
              APPROVAL_STATUS="pending"
              while [ "$APPROVAL_STATUS" == "pending" ]; do
                # Query the deployment status API for the workflow run
                approval_response=$(gh api /repos/${{ github.repository }}/actions/workflows/${{ github.workflow }}.yml/runs/${{ github.run_id }}/jobs)
                APPROVAL_STATUS=$(echo "$approval_response" | jq -r '.[0].conclusion')

                if [ "$APPROVAL_STATUS" == "success" ]; then
                  echo "Approval granted for $env."
                  break
                fi

                if [ "$APPROVAL_STATUS" == "failure" ]; then
                  echo "Approval for $env was rejected. Stopping workflow."
                  exit 1
                fi

                echo "Approval still pending for $env. Retrying..."
                sleep 30  # Check every 30 seconds
              done
            fi

            # Step 3: Trigger Test workflow for the current environment after approval
            echo "====================================="
            echo "Triggering Test workflow for $env"
            echo "====================================="
            gh workflow run reusable-test.yml --ref feature-branch -F environment=$env
            echo "Waiting for test workflow ($env) to complete..."
            sleep 30  # Wait for test workflow to finish
          done
