name: Build, Deploy, and Test Workflow

on:
  push:
    branches:
      - feature-branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: build-artifacts
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: '11'

      - name: Build with Maven
        run: |
          echo "Simulating Maven build..."
          # mvn clean install
          echo "Dummy build completed."

      # - name: Upload Build Artifacts
      #   id: upload_artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: build-artifacts
      #     path: target/*.jar

  deploy-and-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup GitHub CLI
        run: |
          echo "Setting up GitHub CLI"
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Define Environments
        id: define_envs
        run: echo "ENVIRONMENTS=dev sit prod" >> $GITHUB_ENV

      - name: Deploy and Test Sequentially
        run: |
          for env in $ENVIRONMENTS; do
            echo "====================================="
            echo "Triggering Deploy workflow for $env"
            echo "====================================="
            
            # Trigger reusable deploy workflow
            gh workflow run reusable-deploy.yml --ref feature-branch -F environment=$env

            echo "Waiting for deploy workflow to complete..."
            # Simulate waiting for deploy completion
            sleep 10
            echo "Deploy for $env completed."

            if [ "$env" != "dev" ]; then
              echo "Waiting for approval to proceed with $env..."
              # Simulate waiting for approval
              sleep 10
            fi

            echo "====================================="
            echo "Triggering Test workflow for $env"
            echo "====================================="
            
            # Trigger reusable test workflow
            gh workflow run reusable-test.yml --ref feature-branch -F environment=$env

            echo "Waiting for test workflow to complete..."
            # Simulate waiting for test completion
            sleep 10
            echo "Tests for $env completed successfully."
          done
