name: Build and Deploy Java Application

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  workflow_dispatch:  # Allow manual triggers

jobs:
  # Stage 1: Build
  build:
    name: Build Java Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: target/*.jar
  test:
    name: Test Java Code
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: test  # Triggers approval-based email notifications
    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Run Tests
      - name: Run Tests
        run: |
          mvn test | tee test-output.log
          echo "Test run completed."

      # Step 3: Parse Test Results
      - name: Extract Test Results
        id: test-results
        run: |
          TOTAL=$(grep -oP '<testsuite .+? tests="\K\d+' target/surefire-reports/*.xml | paste -sd+ | bc)
          FAILED=$(grep -oP '<testsuite .+? failures="\K\d+' target/surefire-reports/*.xml | paste -sd+ | bc)
          SKIPPED=$(grep -oP '<testsuite .+? skipped="\K\d+' target/surefire-reports/*.xml | paste -sd+ | bc)
          echo "::set-output name=total::$TOTAL"
          echo "::set-output name=failed::$FAILED"
          echo "::set-output name=skipped::$SKIPPED"

      # Step 4: Notify via Environment Approval
      - name: Notify Manager with Test Results
        run: |
          echo "### Test Results Summary" > summary.md
          echo "- Total Tests: ${{ steps.test-results.outputs.total }}" >> summary.md
          echo "- Failed Tests: ${{ steps.test-results.outputs.failed }}" >> summary.md
          echo "- Skipped Tests: ${{ steps.test-results.outputs.skipped }}" >> summary.md
          cat summary.md
        env:
          TOTAL_TESTS: ${{ steps.test-results.outputs.total }}
          FAILED_TESTS: ${{ steps.test-results.outputs.failed }}
          SKIPPED_TESTS: ${{ steps.test-results.outputs.skipped }}


  # Stage 3: Deploy to Development
  deploy-Dev:
    name: Deploy to Dev Environment
    needs: test
    uses: SakshiNadagoudra/Reusable-github-workflows/.github/workflows/reusable-deploy.yml@main  # Reference the reusable workflow
    with:
      environment: dev  # Pass the environment name to the reusable workflow

  # Stage 4: Deploy to Production
  deploy-Prod:
    name: Deploy to Production
    needs: deploy-Dev
    uses: SakshiNadagoudra/Reusable-github-workflows/.github/workflows/reusable-deploy.yml@main  # Reference the reusable workflow
    with:
      environment: production