name: Build, Deploy, and Test Workflow

on:
  push:
    branches:
      - feature-branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: build-artifacts
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: '11'

      - name: Build with Maven
        run: |
          echo "Simulating Maven build..."
          # mvn clean install
          echo "Dummy build completed."

  deploy-and-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Define Environments
        id: define_envs
        run: echo "ENVIRONMENTS=dev sit uat prod" >> $GITHUB_ENV

      - name: Deploy and Test Sequentially
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Pass the GitHub token for authentication
        run: |
          for env in $ENVIRONMENTS; do
            echo "====================================="
            echo "Triggering Deploy workflow for $env"
            echo "====================================="
            
            # Trigger reusable deploy workflow
            deploy_output=$(gh workflow run reusable-deploy.yml --ref feature-branch -F environment=$env)
            echo "Deploy workflow triggered for $env. Output: $deploy_output"

            echo "Waiting for deploy workflow to complete..."
            # Simulate waiting for deploy completion
            sleep 10
            echo "Deploy for $env completed."

            # Only for environments other than 'dev', wait for approval
            if [ "$env" != "dev" ]; then
              echo "Waiting for approval to proceed with $env..."
              approval_status="pending"
              while [ "$approval_status" != "approved" ]; do
                # Fetch approval status from the deploy workflow (use your preferred method to check approval)
                approval_status="approved"  # Simulate approval (you will need to implement the actual check here)
                echo "Approval status: $approval_status"
                sleep 10  # Wait before checking again (to avoid constant polling)
              done
              echo "Approval granted for $env."
            fi

            # Trigger the test workflow after approval (for dev and other environments)
            echo "====================================="
            echo "Triggering Test workflow for $env"
            echo "====================================="
            test_output=$(gh workflow run reusable-test.yml --ref feature-branch -F environment=$env)
            echo "Test workflow triggered for $env. Output: $test_output"

            echo "Waiting for test workflow to complete..."
            # Simulate waiting for test completion
            sleep 10
            echo "Tests for $env completed successfully."
          done
