name: Build and Deploy Java Application

on:
  push:
    branches:
      - feature-branch  # Replace with your target branch
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup GitHub CLI
        run: |
          echo "Setting up GitHub CLI"
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Deploy and Test Environments
        env:
            GH_TOKEN: ${{ github.token }}
        run: |
            environments=("dev" "sit" "uat" "prod")
            
            for env in "${environments[@]}"; do
              echo "Starting deployment to $env environment"
              
              # Trigger deploy workflow and capture the run ID
              run_output=$(gh workflow run .github/workflows/deploy.yml -f environment=$env -r feature-branch)
              echo "$run_output"
              sleep 10  # Wait for workflow to start
              
              # Get the run ID from the latest workflow run
              run_id=$(gh run list --workflow=deploy.yml --limit 1 | awk 'NR==1{print $7}')
              echo "Deployment started with Run ID: $run_id"
              
              # Wait for deployment completion or approval
              while true; do
                status=$(gh run view "$run_id" --json status -q '.status')
                if [ "$status" = "completed" ]; then
                  conclusion=$(gh run view "$run_id" --json conclusion -q '.conclusion')
                  if [ "$conclusion" = "success" ]; then
                    echo "✓ Deploy to $env completed successfully"
                    break
                  else
                    echo "✗ Deploy to $env failed or was cancelled"
                    exit 1
                  fi
                elif [ "$status" = "waiting" ]; then
                  echo "Waiting for environment approval in $env..."
                else
                  echo "Deployment in progress..."
                fi
                sleep 20
              done
              
              # Only proceed with tests if deployment was successful
              echo "Starting tests for $env environment"
              gh workflow run .github/workflows/test.yml -f environment=$env -r feature-branch
              sleep 10
              
              # Get the test run ID
              test_run_id=$(gh run list --workflow=test.yml --limit 1 | awk 'NR==1{print $7}')
              echo "Test started with Run ID: $test_run_id"
              
              # Wait for test completion
              while true; do
                status=$(gh run view "$test_run_id" --json status -q '.status')
                if [ "$status" = "completed" ]; then
                  conclusion=$(gh run view "$test_run_id" --json conclusion -q '.conclusion')
                  if [ "$conclusion" = "success" ]; then
                    echo "✓ Tests for $env completed successfully"
                    break
                  else
                    echo "✗ Tests for $env failed"
                    exit 1
                  fi
                fi
                echo "Tests in progress..."
                sleep 20
              done
              
              echo "----------------------------------------"
            done