name: Build and Deploy Java Application

on:

  pull_request:
    branches:
      - release-branch
  workflow_dispatch:  # Allow manual triggers

jobs:
  # Stage 1: Build
  build:
    name: Build Java Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: target/*.jar

  # Stage 3: Deploy to Development
  deploy-dev:
    name: Deploy to Dev Environment
    needs: test
    uses: SakshiNadagoudra/Reusable-github-workflows/.github/workflows/reusable-deploy.yml@main  # Reference the reusable workflow
    with:
      environment: dev  # Pass the environment name to the reusable workflow
  
  test-uat:
    name: Test in Uat
    needs: deploy-dev
    uses: SakshiNadagoudra/Reusable-github-workflows/.github/workflows/reusable-test.yml@main
    with:
      environment: uat

  # Stage 3: Deploy to Development
  deploy-uat:
    name: Deploy to Uat Environment
    needs: test-uat
    uses: SakshiNadagoudra/Reusable-github-workflows/.github/workflows/reusable-deploy.yml@main  # Reference the reusable workflow
    with:
      environment: uat
  
  test-prod:
    name: Test in Prod
    needs: deploy-uat
    uses: SakshiNadagoudra/Reusable-github-workflows/.github/workflows/reusable-test.yml@main
    with:
      environment: prod

  # Stage 4: Deploy to Production
  deploy-Prod:
    name: Deploy to Production
    needs: test-prod
    uses: SakshiNadagoudra/Reusable-github-workflows/.github/workflows/reusable-deploy.yml@main  # Reference the reusable workflow
    with:
      environment: production