name: Reusable Test Workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      environment:
        description: "The environment to deploy to"
        required: true
        type: string

jobs:
  test:
    name: Test in ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Tests
        run: |
          echo "Running tests in ${{ inputs.environment }}"
          echo "This is a dummy test report for the POC." > test-report.txt

      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: test-report.txt

      - name: Notify Manager with Test Report and Approval Link
        uses: actions/github-script@v6
        with:
          script: |
            const repository = context.repo.repo;
            const runId = context.runId;
            const environment = '${{ inputs.environment }}';  // Environment passed from workflow
            const nextEnvironment = environment === 'dev' ? 'sit' : (environment === 'sit' ? 'prod' : null);
            if (!nextEnvironment) {
              console.log('No next environment to deploy to.');
              return;
            }

            // Fetch the next deploy workflow run ID
            const nextDeployRun = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'reusable-deploy.yml',
              event: 'workflow_dispatch',
              status: 'in_progress',
              per_page: 1
            });

            const nextDeployRunId = nextDeployRun.data.workflow_runs.length > 0 ? nextDeployRun.data.workflow_runs[0].id : null;
            if (!nextDeployRunId) {
              console.log('Unable to find the next deploy workflow run ID.');
              return;
            }

            const workflowUrl = `https://github.com/${context.repo.owner}/${repository}/actions/runs/${runId}`;
            const approvalUrl = `https://github.com/${context.repo.owner}/${repository}/actions/runs/${nextDeployRunId}`;
            const artifactUrl = `https://github.com/${context.repo.owner}/${repository}/suites/${runId}/artifacts`;

            const subject = "Test Execution Complete - Approval Needed";
            const message = `
            **Subject:** ${subject}

            Hi there,

            Test execution is complete. Please review the test report:

            [Download Test Report](${artifactUrl})

            Workflow details: ${workflowUrl}

            To approve and proceed to the next environment ${nextEnvironment}, please visit the following approval link:
            [Approve Deployment](${approvalUrl})
            
            Thanks,
            GitHub-BMO
            `;

            console.log(message);

            // Notify using GitHub API (e.g., comment on the commit)
            await github.rest.repos.createCommitComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.sha,
              body: message,
            });
