name: Reusable Manager Approval Workflow

on:
  workflow_call:
    inputs:
      approvers:
        description: 'GitHub usernames of approvers (comma-separated)'
        required: true
        type: string

jobs:
  approval:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for approval
        uses: peter-evans/approve-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}


      
