name: Reusable Deploy Workflow

on:
  workflow_call:
    inputs:
      environment:
        description: "The environment to deploy to"
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: List Artifacts
        uses: actions/github-script@v6
        with:
          script: |
            const artifacts = await github.rest.actions.listArtifactsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            console.log("Available artifacts:", artifacts.data.artifacts);

      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifacts

      - name: Deploy Application
        run: |
          echo "Deploying application to ${{ inputs.environment }}"
