name: Build and Deploy Java Application

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  workflow_dispatch:  # Allow manual triggers

permissions:
  contents: write
  issues: write  # Ensure the GITHUB_TOKEN can create issues

jobs:
  # Stage 1: Build
  build:
    name: Build Java Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: target/*.jar

  # Stage 2: Testing
  test:
    name: Test Java Code
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: test  # Reference the test environment for approval gates
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Tests
        run: mvn test

  # Stage 3: Deploy to Development
  deploy-Dev:
    name: Deploy to Dev Environment
    needs: test
    uses: SakshiNadagoudra/Reusable-github-workflows/.github/workflows/reusable-deploy.yml@main  # Reference the reusable workflow
    with:
      environment: dev  # Pass the environment name to the reusable workflow

    steps:
      - name: Notify Manager for Approval (Dev)
        run: |
          gh issue create --title "Approval Needed for Dev Deployment" --body "The deployment to the Dev environment is pending approval. Please review and approve." --assignee manager-github-username

  # Stage 4: Deploy to Production
  deploy-Prod:
    name: Deploy to Production
    needs: deploy-Dev
    uses: SakshiNadagoudra/Reusable-github-workflows/.github/workflows/reusable-deploy.yml@main  # Reference the reusable workflow
    with:
      environment: production  # Pass the environment name to the reusable workflow

    steps:
      - name: Notify Manager for Approval (Prod)
        run: |
          gh issue create --title "Approval Needed for Prod Deployment" --body "The deployment to the Production environment is pending approval. Please review and approve." --assignee manager-github-username
