name: Reusable Manager Approval Workflow

on:
  workflow_call:
    inputs:
      approvers:
        description: 'GitHub usernames of approvers (comma-separated)'
        required: true
        type: string

jobs:
  approval:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Manager Approval
        uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          approvers: "manager-github-username"  # Replace with the manager's GitHub username
          allow-empty-comments: true


      
