name: Reusable Deploy Workflow

on:
  workflow_call:
    inputs:
      environment:
        description: "The environment to deploy to"
        required: true
        type: string

jobs:
  deploy:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }} # Use environment protection if enabled

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: artifacts

      - name: Deploy Application
        run: |
          echo "Deploying to ${{ inputs.environment }} environment"
          ls artifacts  # List downloaded artifacts
          # Add deployment logic here
