name: Reusable Deploy Workflow

on:
  workflow_call:
    inputs:
      environment:
        description: "The environment to deploy to"
        required: true
        type: string
  workflow_dispatch:
    inputs:
      environment:
        description: "The environment to deploy to"
        required: true
        type: string

jobs:
  deploy:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }} # Attach the job to the specified environment for approval gates

    steps:
      - name: Checkout Code
        if: ${{ inputs.environment == 'dev' }}
        uses: actions/checkout@v3

      - name: Download Build Artifacts from Previous Environment
        if: ${{ inputs.environment != 'dev' }}
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts  # Ensure this matches the artifact name in the main workflow

      - name: Deploy Application
        run: |
          echo "Deploying to the ${{ inputs.environment }} environment"
          # Add your deployment logic here (e.g., copying files, running scripts)
