name: Reusable Deploy Workflow

on:
  workflow_call:
    inputs:
      environment:
        description: "The environment to deploy to"
        required: true
        type: string
      run_id:
        description: "The run ID for downloading artifacts"
        required: true
        type: string
  workflow_dispatch:
    inputs:
      environment:
        description: "The environment to deploy to"
        required: true
        type: string
      run_id:
        description: "The run ID for downloading artifacts"
        required: true
        type: string

jobs:
  deploy:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}

    steps:
      - name: Set GH_TOKEN
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Set GH_TOKEN for GitHub CLI
        run: echo "GH_TOKEN has been set."

      - name: Download Build Artifacts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Downloading artifacts from run ID ${{ inputs.run_id }}"
          gh run download ${{ inputs.run_id }} --dir artifacts

      - name: Deploy Application
        run: |
          echo "Deploying to the ${{ inputs.environment }} environment"
          ls artifacts  # List downloaded artifacts
          # Add deployment logic here
